---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: cqi
  description: This role installs Citrix Connection Quality Indicator on Windows systems.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'

collections:
  - ansible.windows

dependencies: []
