---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: cqi
  description: This role installs Citrix Connection Quality Indicator on Windows systems.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.windows

dependencies: []
