---
- name: Verify
  hosts:
    - subjects
  gather_facts: false
  tasks:
    - name: Check if the PVS Target Device software is installed
      ansible.windows.win_powershell:
        script: |
          $Ansible.Changed = $false

          $PVSConsole = ([array](Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "Citrix Provisioning Target Device*" }))

          $Ansible.Result = $PVSConsole.Count -gt 0
      register: _pvs_console_installed

    - name: Verify that the PVS Target Device software is installed
      ansible.builtin.assert:
        that:
          - _pvs_console_installed.result
        fail_msg: The Citrix PVS Target Device software is not installed.
        success_msg: The Citrix PVS Target Device software is installed.
