---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: pvs_console
  description: This role installs the Citrix Provisioning Console on Windows systems.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - chocolatey.chocolatey

dependencies: []
