---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: licensing
  description: This role installs the Citrix Licensing server on Windows servers.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows

dependencies: []
