---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: win
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 8192
    cpus: 2
    provider_options:
      default_prefix: citrix_pvs_console_
    groups:
      - subjects
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        _ctxpvs_version: ${MOLECULE_CITRIX_PVS_VERSION:-2411}
        _ctxpvs_console_installer_source: "../../../../files/pvs_console/{{ _ctxpvs_version }}"
        ctxpvs_console_installer_path: "C:\\Windows\\Temp\\pvs_console\\{{ _ctxpvs_version }}\\PVS_Console_x64.exe"
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
verifier:
  name: ansible
