---
- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Create temporary directory
      ansible.windows.win_file:
        path: C:\Windows\Temp\pvs_console
        state: directory

    - name: Copy Citrix PVS Console installer
      ansible.windows.win_copy:
        src: "{{ _ctxpvs_console_installer_source }}"
        dest: C:\Windows\Temp\pvs_console\
