---
- name: Gather OS facts
  when:
    - ansible_distribution is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution

- name: Validate OS
  ansible.builtin.assert:
    that:
      - ansible_os_family == 'Windows'
    fail_msg: "This role only supports Windows.  {{ ansible_distribution }} is not supported."
    success_msg: "This role supports {{ ansible_distribution }}."
