---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Install
  ansible.builtin.import_tasks: install.yml

- name: Configure
  when:
    - not _ctxpvs_server_is_configured or
      _ctxpvs_server_install_result is changed
  ansible.builtin.include_tasks: configure.yml
