---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: win_server_vda
  description: This role installs and configures Citrix Virtual Delivery Agent for Multi-session OS on Windows servers.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections:
  - ansible.windows
  - community.windows

dependencies: []
