---
- name: 'Check if scheduled task exists | {{ item.name }}'
  community.windows.win_scheduled_task_stat:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  register: _ctxvda_task_info

- name: 'Ensure scheduled task is disabled | {{ item.name }}'
  when:
    - _ctxvda_task_info.task_exists
  community.windows.win_scheduled_task:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    enabled: false
