---
- name: 'Check if service exists | {{ item.display_name }}'
  ansible.windows.win_service_info:
    name: "{{ item.name }}"
  register: _ctxvda_service_info

- name: 'Ensure service is stopped and disabled | {{ item.display_name }}'
  when:
    - _ctxvda_service_info.exists
  ansible.windows.win_service:
    name: "{{ item.name }}"
    state: stopped
    start_mode: disabled
