---
- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Copy Citrix VDA installer
      ansible.windows.win_copy:
        src: "{{ _ctxvda_installer }}"
        dest: "{{ ctxvda_installer_path }}"
