---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: pvs_target
  description: This role installs the Citrix Provisioning Target Device software on Windows systems.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'

collections:
  - ansible.windows
  - chocolatey.chocolatey

dependencies: []
