---
galaxy_info:
  author: Jim Tarpley
  namespace: trippsc2
  role_name: pvs_target
  description: This role installs the Citrix Provisioning Target Device software on Windows systems.

  license: MIT

  min_ansible_version: '2.15'

  platforms:
    - name: Windows
      versions:
        - '2019'
        - '2022'

collections: []

dependencies: []
