---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: win
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 8192
    cpus: 2
    provider_options:
      default_prefix: citrix_cqi_
    groups:
      - subjects
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        _ctxvda_installer: ./files/VDAServerSetup_2407.exe
        _ctxcqi_installer: ./files/CitrixCQI.msi
        ctxvda_installer_path: C:\Windows\Temp\VDAServerSetup_2407.exe
        ctxvda_controller_list:
          - dc1.test.loc
          - dc2.test.loc
        ctxcqi_installer_path: C:\Windows\Temp\CitrixCQI.msi
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
verifier:
  name: ansible
