---
- name: Prepare DC
  hosts:
    - dc
  roles:
    - role: trippsc2.ad.testing_domain_controller

- name: Prepare member server
  hosts:
    - windows_domain_members
  gather_facts: false
  roles:
    - role: trippsc2.ad.testing_win_member

- name: Prepare MSSQL
  hosts:
    - mssql
  pre_tasks:
    - name: Copy SQL Server installation media
      ansible.windows.win_copy:
        src: "{{ _mssql_setup_source_path }}"
        dest: "{{ mssql_setup_path | win_dirname }}"
  roles:
    - role: trippsc2.mssql.install

- name: Prepare
  hosts:
    - subjects
  pre_tasks:
    - name: Create temporary directories
      loop:
        - pvs_console
        - pvs_server
      ansible.windows.win_file:
        path: "C:\\Windows\\Temp\\{{ item }}"
        state: directory

    - name: Copy Citrix Licensing installer files
      ansible.windows.win_copy:
        src: "{{ _ctxpvs_licensing_installer_source }}"
        dest: C:\Windows\Temp\

    - name: Copy Citrix PVS console installer files
      ansible.windows.win_copy:
        src: "{{ _ctxpvs_console_installer_source }}"
        dest: C:\Windows\Temp\pvs_console

    - name: Copy Citrix PVS server installer files
      ansible.windows.win_copy:
        src: "{{ _ctxpvs_server_installer_source }}"
        dest: C:\Windows\Temp\pvs_server

    - name: Create Store folder
      ansible.windows.win_file:
        path: "{{ ctxpvs_default_store_path }}"
        state: directory
  roles:
    - role: trippsc2.citrix.licensing
