---
- name: Prepare
  hosts:
    - subjects
  tasks:
    - name: Copy Citrix PVS installer files
      ansible.windows.win_copy:
        src: "{{ _ctxpvs_installer_source }}"
        dest: C:\Windows\Temp\
