---
name: Generate Role Docs - pvs_console role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-pvs_console.yml
      - roles/pvs_console/.aar_doc.yml
      - roles/pvs_console/meta/argument_specs.yml
      - roles/pvs_console/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  docs:
    name: Generate pvs_console role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'pvs_console'
