---
name: Generate Role Docs - pvs_target role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-pvs_target.yml
      - roles/pvs_target/.aar_doc.yml
      - roles/pvs_target/meta/argument_specs.yml
      - roles/pvs_target/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  docs:
    name: Generate pvs_target role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'pvs_target'
