---
name: Generate Role Docs - win_server_vda role
'on':
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs-win_server_vda.yml
      - roles/win_server_vda/.aar_doc.yml
      - roles/win_server_vda/meta/argument_specs.yml
      - roles/win_server_vda/meta/main.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-win_server_vda.yml
      - roles/win_server_vda/.aar_doc.yml
      - roles/win_server_vda/meta/argument_specs.yml
      - roles/win_server_vda/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  docs:
    name: Generate win_server_vda role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'win_server_vda'
