---
name: Generate Role Docs - licensing role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-licensing.yml
      - roles/licensing/.aar_doc.yml
      - roles/licensing/meta/argument_specs.yml
      - roles/licensing/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  docs:
    name: Generate licensing role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'licensing'
