---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/cqi/.aar_doc.yml
      - roles/cqi/README.md
      - roles/cqi/meta/argument_specs.yml
      - roles/cqi/meta/main.yml
      - roles/licensing/.aar_doc.yml
      - roles/licensing/README.md
      - roles/licensing/meta/argument_specs.yml
      - roles/licensing/meta/main.yml
      - roles/pvs_console/.aar_doc.yml
      - roles/pvs_console/README.md
      - roles/pvs_console/meta/argument_specs.yml
      - roles/pvs_console/meta/main.yml
      - roles/pvs_server/.aar_doc.yml
      - roles/pvs_server/README.md
      - roles/pvs_server/meta/argument_specs.yml
      - roles/pvs_server/meta/main.yml
      - roles/pvs_target/.aar_doc.yml
      - roles/pvs_target/README.md
      - roles/pvs_target/meta/argument_specs.yml
      - roles/pvs_target/meta/main.yml
      - roles/wem_agent/.aar_doc.yml
      - roles/wem_agent/README.md
      - roles/wem_agent/meta/argument_specs.yml
      - roles/wem_agent/meta/main.yml
      - roles/win_server_vda/.aar_doc.yml
      - roles/win_server_vda/README.md
      - roles/win_server_vda/meta/argument_specs.yml
      - roles/win_server_vda/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  docs_cqi:
    name: Generate cqi role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'cqi'
  docs_licensing:
    name: Generate licensing role documentation
    permissions:
      contents: write
    needs: docs_cqi
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'licensing'
  docs_pvs_console:
    name: Generate pvs_console role documentation
    permissions:
      contents: write
    needs: docs_licensing
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'pvs_console'
  docs_pvs_server:
    name: Generate pvs_server role documentation
    permissions:
      contents: write
    needs: docs_pvs_console
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'pvs_server'
  docs_pvs_target:
    name: Generate pvs_target role documentation
    permissions:
      contents: write
    needs: docs_pvs_server
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'pvs_target'
  docs_wem_agent:
    name: Generate wem_agent role documentation
    permissions:
      contents: write
    needs: docs_pvs_target
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'wem_agent'
  docs_win_server_vda:
    name: Generate win_server_vda role documentation
    permissions:
      contents: write
    needs: docs_wem_agent
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'win_server_vda'
