---
name: Molecule - wem_agent role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/wem_agent/**
      - '!roles/wem_agent/.aar_doc.yml'
      - '!roles/wem_agent/README.md'
      - '!roles/wem_agent/meta/argument_specs.yml'
      - '!roles/wem_agent/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/wem_agent/**
      - '!roles/wem_agent/.aar_doc.yml'
      - '!roles/wem_agent/README.md'
      - '!roles/wem_agent/meta/argument_specs.yml'
      - '!roles/wem_agent/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  molecule:
    name: Run Molecule tests
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
          - w11_23h2_base
          - w10_22h2_base
        version:
          - '2503'
          - '2411'
          - '2407'
          - '2402'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.citrix'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          ln -s ~/files/ansible-collection-citrix ./files
          cd ./roles/wem_agent
          molecule test
          rm -rf ~/.ansible/collections/ansible_collections/*
          rm ../../files
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
          MOLECULE_CITRIX_WEM_VERSION: ${{ matrix.version }}
