---
name: Molecule - cqi role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/cqi/**
      - '!roles/cqi/.aar_doc.yml'
      - '!roles/cqi/README.md'
      - '!roles/cqi/meta/argument_specs.yml'
      - '!roles/cqi/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/cqi/**
      - '!roles/cqi/.aar_doc.yml'
      - '!roles/cqi/README.md'
      - '!roles/cqi/meta/argument_specs.yml'
      - '!roles/cqi/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.citrix'
jobs:
  molecule:
    name: Run Molecule test
    uses: trippsoft/github-actions/.github/workflows/molecule.yml@main
    with:
      working_directory: 'trippsc2.citrix'
      role_name: 'cqi'
      box: ${{ matrix.box }}
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
